name: Deploy Echoserver to GKE
on:
  push:
    branches:
      - main
env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: gke-central1-cluster
  GKE_ZONE: us-central1-a
  DEPLOYMENT_NAME: echoserver
  IMAGE: echoserver
  NAMESPACE: prod
  PROJECT_NUMBER: 603509934273
jobs:
  deploy:
    name: Deploy to GKE
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        id: auth
        
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: projects/603509934273/locations/global/workloadIdentityPools/gke-lab-pool-v2/providers/gke-lab-provider-fixed
          service_account: gke-lab-sa@${{ env.PROJECT_ID }}.iam.gserviceaccount.com

      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.PROJECT_ID }}

      - name: Get GKE credentials
        uses: google-github-actions/get-gke-credentials@v2
        with:
          cluster_name: ${{ env.GKE_CLUSTER }}
          location: ${{ env.GKE_ZONE }}
          project_id: ${{ env.PROJECT_ID }}

      - name: Deploy to GKE
        run: |
          kubectl apply -f k8s/deployment.yaml
          kubectl apply -f k8s/service.yaml
          kubectl rollout status deployment/${{ env.DEPLOYMENT_NAME }} -n ${{ env.NAMESPACE }}
          kubectl get services -n ${{ env.NAMESPACE }} -o wide
      - name: Verify gcloud Auth
        run: |
          gcloud auth list
          gcloud config list project
